# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ready2scanlate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ready2scanlate.proto\x12\x15rafi12.ready2scanlate\"\"\n\x0bSyncTimeReq\x12\x13\n\x0b\x63lient_time\x18\x01 \x01(\x12\"\"\n\x0bSyncTimeRsp\x12\x13\n\x0bserver_time\x18\x01 \x01(\x12\"\x94\x01\n\rSocketMessage\x12;\n\rsync_time_req\x18\x01 \x01(\x0b\x32\".rafi12.ready2scanlate.SyncTimeReqH\x00\x12;\n\rsync_time_rsp\x18\x02 \x01(\x0b\x32\".rafi12.ready2scanlate.SyncTimeRspH\x00\x42\t\n\x07messageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ready2scanlate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYNCTIMEREQ._serialized_start=47
  _SYNCTIMEREQ._serialized_end=81
  _SYNCTIMERSP._serialized_start=83
  _SYNCTIMERSP._serialized_end=117
  _SOCKETMESSAGE._serialized_start=120
  _SOCKETMESSAGE._serialized_end=268
# @@protoc_insertion_point(module_scope)
